language: ru
pipeline:
#- name: SpacyNLP
#  model: "ru_core_news_md"
#- name: SpacyTokenizer
#- name: SpacyFeaturizer
- name: WhitespaceTokenizer
  token_pattern: (?u)\b\w+\b
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "word"
  min_ngram: 1
  max_ngram: 1
  OOV_token: "oov"
  use_shared_vocab: True
- name: DIETClassifier
  epochs: 200
  ranking_length: 5
  random_seed: 1
  constrain_similarities: True
  model_confidence: linear_norm
- name: DucklingEntityExtractor
  url: http://localhost:8000
  dimensions:
  - email
  - number
  - amount-of-money
- name: EntitySynonymMapper
- name: ResponseSelector
  constrain_similarities: True
  model_confidence: linear_norm
  retrieval_intent: out_of_scope
  scale_loss: false
  epochs: 100
- name: ResponseSelector
  constrain_similarities: True
  model_confidence: linear_norm
  retrieval_intent: faq
  scale_loss: false
  epochs: 100
- name: ResponseSelector
  constrain_similarities: True
  model_confidence: linear_norm
  retrieval_intent: chitchat
  scale_loss: false
  epochs: 100
- name: ResponseSelector
  constrain_similarities: True
  model_confidence: linear_norm
  retrieval_intent: helpcreate
  scale_loss: false
  epochs: 200
- name: ResponseSelector
  constrain_similarities: True
  model_confidence: linear_norm
  retrieval_intent: helpcheck
  scale_loss: false
  epochs: 200
- name: FallbackClassifier
  threshold: 0.7
policies:
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True
  - name: AugmentedMemoizationPolicy
    max_history: 6
  - name: TEDPolicy
    max_history: 10
    epochs: 20
    batch_size:
    - 32
    - 64
#    constrain_similarities: True
#    model_confidence: linear_norm

